apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qua 
  janus-idp.io/tekton: qua
  backstage.io/kubernetes-id: qua
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qua
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  