apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qua
  janus-idp.io/tekton: qua
  backstage.io/kubernetes-id: qua
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qua
resources: 
- deployment.yaml
- route.yaml
- service.yaml
