apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: qua
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qua 
  name: qua
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: qua
    weight: 100 
